FIX: check ends_at in migration to event date (#77)
Don't create event date when original_ends_at doesn't exist.

This mean that event markdown is not correct

It was throwing error: undefined method `<' for nil:NilClass>