FIX: check ends_at in migration to event date
Assign finished_at only if original_ends_at is set.

It was throwing error: undefined method `<' for nil:NilClass>